version: '3.8'

services:
  postgres:
    container_name: postgres_dev
    image: postgres    
    env_file:
    - .env
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - 5432
    networks:
      - dev-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dev-network
    expose:
      - 5050
    restart: unless-stopped

networks:
  dev-network:
    name: dev-network
    driver: bridge

volumes:
    postgres:
    pgadmin:
